use_frameworks!
target 'TapTapSee' do

pod 'FlurrySDK', '~> 5.0.0'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.0.7'
pod 'Appirater', '~> 2.0.2'
pod 'GroundControl', '~> 2.1.0'
pod 'RequestUtils'
pod 'CloudSight'
pod 'TMReachability', :git => 'https://github.com/albertbori/Reachability'
end
